### ISSUE TITLE
 doc1 = json.loads(redisd.get('codred-doc-' + doc1_id))     doc2 = json.loads(redisd.get('codred-doc-' + doc2_id))问题

### ISSUE THREAD

**Issue by Veranece** [aailabkaist/REIC#1]
作者您好！当我在尝试复现代码的时候，发现了这样两句代码，    doc1 = json.loads(redisd.get('codred-doc-' + doc1_id))
    doc2 = json.loads(redisd.get('codred-doc-' + doc2_id))。经过我的排查后，发现是从本地redis数据库中读取出一些数据，而我下载的代码文件和codred数据中都没有这部分数据，请问是我遗漏了什么吗？感谢您的回答！

**Comment by byeonghu-na** [comment]
Thank you for your interest in our research. The part you mentioned requires the data to be prepared according to the instructions in the [CodRED repository](https://github.com/thunlp/CodRED?tab=readme-ov-file#baseline).
